spring:
  application:
    name: smart-expiry-server
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/smart_expiry}
    username: ${DB_USERNAME:smart_expiry}
    password: ${DB_PASSWORD:smart_expiry}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  error:
    include-message: never
    include-stacktrace: never

logging:
  level:
    org.hibernate.SQL: WARN
