"""Generate ArkTS defaults from the shared attention contract, without network access."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
data = json.loads((root / 'algorithm/contracts/attention-rules.json').read_text(encoding='utf-8'))
fields = '\n'.join(f"  {key}: {'string' if isinstance(value, str) else 'number'};" for key, value in data.items())
source = '// Generated by scripts/sync_attention_fixture.py. Edit algorithm/contracts/attention-rules.json.\n'
source += 'export interface AttentionRules {\n' + fields + '\n}\n'
source += 'export const DEFAULT_ATTENTION_RULES: AttentionRules = ' + json.dumps(data, ensure_ascii=False, indent=2) + ';\n'
(root / 'entry/src/main/ets/algorithm/AttentionRules.ets').write_text(source, encoding='utf-8')
